### PR TITLE
Added gpl affero v3 license.

### PR DESCRIPTION
**Pull request by briantoth**

### CODE REVIEW

**Comment by billbindi** [comment]
Don't really know how to approve, so I'll just do it in a comment.

+1

**Comment by briantoth** [comment]
@miketoth @sfendell @michaeledryan - if you guys are also ok with this can you comment right on the pr?

**Comment by michaeledryan** [comment]
+1

**Comment by miketoth** [comment]
I approve!

**Comment by sfendell-zz** [comment]
+1

**Comment by sfendell-zz** [comment]
+1

**Pull request merged**
